export const SERVICE_DATA = {
  "battery-jumpstart": {
    title: "Battery Jumpstart",
    slug: "battery-jumpstart",
    description: "Quick battery jumpstart service when your car won't start",
    image: "/images/cardService/battery-jumpstart.jpg",
    heroImage: "/images/services/battery-hero.jpg",
    heroTitle: "Battery Jumpstart Service",
    heroSubtitle: "Dead battery? We'll get you started in minutes.",
    heroDescription: "Professional 24/7 battery jumpstart service across Jaipur. Our certified technicians arrive fast with heavy-duty equipment to get your car running again safely.",
    quickStats: [
      { value: "30", unit: "min", label: "Avg. Arrival" },
      { value: "24/7", unit: "", label: "Availability" },
      { value: "100%", unit: "", label: "Success Rate" },
    ],
    overview: {
      title: "Fast, Safe Battery Jumpstart — Anytime, Anywhere",
      paragraphs: [
        "A dead battery is the most common reason cars won't start. Whether it's caused by leaving headlights on, extreme temperatures, or an aging battery, it doesn't have to ruin your day. RJ Roadside Assistance provides rapid battery jumpstart services throughout Jaipur — day or night.",
        "Our technicians arrive equipped with professional-grade jump starters, heavy-duty cables, and diagnostic tools. We don't just jumpstart your vehicle — we test your battery health, check the alternator output, and let you know if a replacement is needed before the next failure.",
        "We handle all vehicle types: hatchbacks, sedans, SUVs, luxury cars, and commercial vehicles. Every jumpstart follows strict safety protocols to protect your vehicle's electrical system.",
      ],
      image: "/images/cardService/battery-jumpstart.jpg",
    },
    features: [
      { title: "24/7 Availability", description: "Round-the-clock service across Jaipur. Call us at 2 AM or 2 PM — we're always ready.", icon: "clock" },
      { title: "Under 30 Min Response", description: "Our dispatch system routes the nearest technician to your location for fastest arrival.", icon: "speed" },
      { title: "Professional Equipment", description: "Heavy-duty jumper packs and cables rated for all battery types including AGM and lithium.", icon: "tool" },
      { title: "Battery Health Check", description: "Free battery voltage and alternator test after every jumpstart to prevent future issues.", icon: "check" },
      { title: "All Vehicle Types", description: "From compact cars to SUVs and commercial vehicles — we carry equipment for every battery.", icon: "car" },
      { title: "No Hidden Fees", description: "Transparent pricing communicated upfront. You approve the cost before we begin work.", icon: "price" },
    ],
    process: [
      { step: "01", title: "Call Us", description: "Call +91-8955836514 or book online. Share your location and vehicle details." },
      { step: "02", title: "We Arrive Fast", description: "The nearest technician is dispatched with professional jump-start equipment." },
      { step: "03", title: "Safe Jumpstart", description: "We connect cables following safety protocols, start your vehicle, and test the system." },
      { step: "04", title: "You're Rolling", description: "Battery tested, vehicle running. We recommend next steps if replacement is needed." },
    ],
    faqs: [
      { question: "How quickly can you reach me?", answer: "Our average response time in Jaipur is under 30 minutes. During peak hours, it may take slightly longer, but we always dispatch the nearest available technician." },
      { question: "Will jumpstarting damage my car?", answer: "No. Our technicians follow manufacturer-recommended procedures with insulated, professional-grade equipment designed to protect your vehicle's electrical system." },
      { question: "What if my battery needs replacement?", answer: "We carry replacement batteries for common vehicle models. If yours needs replacing, we can do it on the spot — no need for a separate trip to a shop." },
      { question: "How much does the service cost?", answer: "Pricing depends on your location and vehicle type. We provide an upfront quote before dispatching, so there are no surprises. Call us for a quick estimate." },
      { question: "Do you service all car brands?", answer: "Yes. We handle all makes and models — Maruti, Hyundai, Honda, Toyota, BMW, Mercedes, and more. Our equipment works with 12V and 24V battery systems." },
    ],
    relatedServices: ["flat-tyre", "emergency-breakdown", "mechanical-fault"],
  },

  "flat-tyre": {
    title: "Flat Tyre Repair",
    slug: "flat-tyre",
    description: "Professional flat tyre repair and replacement service",
    image: "/images/cardService/flat-tyre.jpg",
    heroImage: "/images/services/tyre-hero.jpg",
    heroTitle: "Flat Tyre Service",
    heroSubtitle: "Puncture or blowout? We handle it roadside.",
    heroDescription: "Expert flat tyre repair, replacement, and wheel change service. Our technicians bring tools, spares, and expertise directly to your location — 24/7.",
    quickStats: [
      { value: "30", unit: "min", label: "Avg. Arrival" },
      { value: "24/7", unit: "", label: "Availability" },
      { value: "All", unit: "", label: "Tyre Types" },
    ],
    overview: {
      title: "Roadside Tyre Repair You Can Count On",
      paragraphs: [
        "Flat tyres happen without warning — potholes, nails, sharp debris, or slow leaks can leave you stranded. Changing a tyre on a busy road is dangerous and difficult. That's where RJ Roadside Assistance comes in.",
        "Our technicians arrive with hydraulic jacks, impact wrenches, torque tools, and a selection of spare tyres. We assess the damage, repair the puncture on-site when possible, or replace the tyre with a matching spare. Every installation is torqued to manufacturer specs.",
        "We handle all tyre sizes and vehicle types. Whether you drive a compact hatchback, a heavy SUV, or a luxury sedan, we have the equipment and expertise to get you moving safely.",
      ],
      image: "/images/cardService/flat-tyre.jpg",
    },
    features: [
      { title: "On-Site Repair", description: "Many punctures can be patched right at your location, saving the cost of a new tyre.", icon: "tool" },
      { title: "Spare Tyre Inventory", description: "We carry common tyre sizes for immediate replacement when repair isn't possible.", icon: "check" },
      { title: "Professional Tools", description: "Hydraulic jacks, impact wrenches, and torque wrenches for safe, fast wheel changes.", icon: "speed" },
      { title: "Pressure Check", description: "We check and adjust all four tyres to manufacturer-recommended pressure levels.", icon: "check" },
      { title: "Safety First", description: "Warning cones, wheel chocks, and proper jack placement — every change follows safety protocols.", icon: "clock" },
      { title: "Fair Pricing", description: "Upfront quotes with no hidden charges. Repair is always recommended over replacement when safe.", icon: "price" },
    ],
    process: [
      { step: "01", title: "Report It", description: "Call +91-8955836514. Tell us your location, vehicle type, and which tyre is affected." },
      { step: "02", title: "Technician Arrives", description: "A fully-equipped technician reaches you with jacks, tools, and spare tyres." },
      { step: "03", title: "Assess & Fix", description: "We inspect the damage — patch the puncture on-site or replace with a matching spare." },
      { step: "04", title: "Safe to Drive", description: "Lug nuts torqued to spec, pressure checked. You're safely back on the road." },
    ],
    faqs: [
      { question: "Can you repair my tyre or will it need replacing?", answer: "It depends on the damage. Small punctures in the tread area can usually be patched on-site. Sidewall damage or large tears require replacement for safety." },
      { question: "Do you carry my tyre size?", answer: "We stock common sizes for popular Indian vehicles. If we don't have your exact match, we'll install a temporary spare and help you source the right tyre." },
      { question: "How long does a tyre change take?", answer: "A standard tyre change takes 15-20 minutes. Puncture repair may take 20-30 minutes depending on the damage." },
      { question: "Will you check my other tyres too?", answer: "Yes. We inspect all four tyres for wear, damage, and pressure as part of every flat tyre service — at no extra charge." },
    ],
    relatedServices: ["battery-jumpstart", "towing", "emergency-breakdown"],
  },

  "key-lockout": {
    title: "Key Lockout",
    slug: "key-lockout",
    description: "Emergency key lockout assistance — no damage to your vehicle",
    image: "/images/cardService/key-lockout.jpg",
    heroImage: "/images/services/key-hero.jpg",
    heroTitle: "Key Lockout Service",
    heroSubtitle: "Locked out? We'll get you back in — safely.",
    heroDescription: "Professional vehicle lockout service using specialized tools. We unlock your car without any damage — fast, safe, and available 24/7 across Jaipur.",
    quickStats: [
      { value: "20", unit: "min", label: "Avg. Arrival" },
      { value: "0%", unit: "", label: "Damage Rate" },
      { value: "All", unit: "", label: "Car Models" },
    ],
    overview: {
      title: "Non-Destructive Vehicle Unlocking by Experts",
      paragraphs: [
        "It happens to everyone — keys locked inside, lost, or broken in the lock. Don't try to force your way in or call an unqualified locksmith who might damage your car. RJ Roadside Assistance specialists use professional lockout tools designed for zero-damage entry.",
        "Our technicians are trained in automotive lockout techniques for both traditional key locks and modern electronic/keyless entry systems. We use slim jims, air wedges, and long-reach tools — the same equipment used by authorized dealers.",
        "We verify ownership before unlocking (ID + registration) to ensure security. The entire process typically takes 10-15 minutes with no scratches, dents, or damage to your vehicle.",
      ],
      image: "/images/cardService/key-lockout.jpg",
    },
    features: [
      { title: "Zero Damage Guarantee", description: "Professional tools and techniques designed specifically for non-destructive vehicle entry.", icon: "check" },
      { title: "Fast Response", description: "Lockout specialists typically arrive within 20 minutes across Jaipur city limits.", icon: "speed" },
      { title: "All Lock Types", description: "We handle mechanical locks, electronic locks, keyless entry, and smart key systems.", icon: "car" },
      { title: "Key Extraction", description: "Broken key stuck in the lock? We can extract it safely without damaging the lock cylinder.", icon: "tool" },
      { title: "Ownership Verification", description: "We verify ID and vehicle documents before unlocking — protecting your security.", icon: "check" },
      { title: "24/7 Emergency Service", description: "Locked out at midnight in a parking lot? We're available around the clock.", icon: "clock" },
    ],
    process: [
      { step: "01", title: "Call Immediately", description: "Contact +91-8955836514. Stay with your vehicle and share your exact location." },
      { step: "02", title: "Specialist Arrives", description: "A trained lockout specialist reaches you with professional unlocking tools." },
      { step: "03", title: "Safe Unlock", description: "We verify ownership, then unlock your vehicle using non-destructive techniques." },
      { step: "04", title: "Access Restored", description: "You're back inside your car — no damage, no stress, no hassle." },
    ],
    faqs: [
      { question: "Will unlocking damage my car?", answer: "No. We use professional-grade tools specifically designed for non-destructive entry. Your paint, seals, and locks remain intact." },
      { question: "Can you unlock electronic/smart key cars?", answer: "Yes. Our technicians are trained to work with all modern locking systems including push-button start and keyless entry vehicles." },
      { question: "Why do you verify ownership?", answer: "For your security. We require a valid ID and vehicle registration to ensure we're helping the rightful owner. This protects you against theft." },
      { question: "What if my key broke in the lock?", answer: "We can extract broken keys and help you access your vehicle. We'll also recommend key replacement services for your next step." },
    ],
    relatedServices: ["battery-jumpstart", "emergency-breakdown", "towing"],
  },

  "towing": {
    title: "Towing Service",
    slug: "towing",
    description: "Safe, professional towing for all vehicle types",
    image: "/images/cardService/towing-service.jpg",
    heroImage: "/images/services/towing-hero.jpg",
    heroTitle: "Towing Service",
    heroSubtitle: "Can't drive it? We'll transport it safely.",
    heroDescription: "Professional flatbed and wheel-lift towing for cars, SUVs, and commercial vehicles. Safe loading, secure transport, flexible destinations — available 24/7.",
    quickStats: [
      { value: "45", unit: "min", label: "Avg. Arrival" },
      { value: "All", unit: "", label: "Vehicle Types" },
      { value: "Safe", unit: "", label: "Transport" },
    ],
    overview: {
      title: "Professional Vehicle Towing Across Jaipur",
      paragraphs: [
        "When your vehicle can't be repaired on-site — after an accident, major breakdown, or engine failure — you need reliable towing. RJ Roadside Assistance operates modern flatbed and wheel-lift tow trucks maintained to the highest safety standards.",
        "Our certified drivers follow strict loading and securing protocols. Vehicles are strapped with professional-grade equipment to prevent any movement during transport. We document your vehicle's condition before loading for complete transparency.",
        "We tow to any destination: your home, preferred workshop, dealership, or insurance-approved facility. For accident vehicles, we coordinate with police and insurance companies to streamline the process.",
      ],
      image: "/images/cardService/towing-service.jpg",
    },
    features: [
      { title: "Flatbed Towing", description: "Safest method for luxury cars, AWD vehicles, and cars with transmission issues. All wheels off the ground.", icon: "car" },
      { title: "All Vehicle Types", description: "Cars, SUVs, motorcycles, and light commercial vehicles. Equipment rated for safe transport.", icon: "tool" },
      { title: "Secure Loading", description: "Professional straps, wheel nets, and securing devices prevent any movement during transit.", icon: "check" },
      { title: "Any Destination", description: "Home, workshop, dealership — you choose where your vehicle goes. We serve all Jaipur areas.", icon: "speed" },
      { title: "Accident Assistance", description: "We coordinate with police and insurance companies for accident-related towing and documentation.", icon: "clock" },
      { title: "Vehicle Recovery", description: "Stuck in mud, ditch, or off-road? We provide recovery services to extract your vehicle safely.", icon: "tool" },
    ],
    process: [
      { step: "01", title: "Request Towing", description: "Call +91-8955836514. Provide your location, vehicle type, and preferred destination." },
      { step: "02", title: "Truck Dispatched", description: "The appropriate tow truck (flatbed or wheel-lift) is sent to your location." },
      { step: "03", title: "Safe Loading", description: "We document condition, carefully load your vehicle, and secure it for transport." },
      { step: "04", title: "Delivered Safely", description: "Your vehicle arrives at the destination undamaged. We hand over with condition documentation." },
    ],
    faqs: [
      { question: "What type of tow truck will you send?", answer: "It depends on your vehicle. Flatbed trucks are used for AWD/luxury vehicles and post-accident towing. Wheel-lift trucks work for standard front or rear-wheel drive vehicles." },
      { question: "How far can you tow my vehicle?", answer: "We serve all areas within Jaipur city and surrounding regions. For long-distance towing, call us for availability and pricing." },
      { question: "Can you tow after an accident?", answer: "Yes. We handle accident towing and can coordinate with traffic police and your insurance company. We document vehicle condition for your records." },
      { question: "My car is stuck — can you help?", answer: "Absolutely. We provide vehicle recovery for cars stuck in mud, ditches, or off-road situations using winches and specialized equipment." },
    ],
    relatedServices: ["emergency-breakdown", "mechanical-fault", "flat-tyre"],
  },

  "mechanical-fault": {
    title: "Mechanical Repair",
    slug: "mechanical-fault",
    description: "On-site diagnosis and repair for mechanical issues",
    image: "/images/cardService/mechanical-fault.jpg",
    heroImage: "/images/services/mechanic-hero.jpg",
    heroTitle: "On-Site Mechanical Repair",
    heroSubtitle: "Mobile workshop. Expert diagnosis. On-the-spot fixes.",
    heroDescription: "Our certified mechanics bring diagnostic tools, parts, and expertise directly to your location. From engine issues to electrical faults, many problems can be fixed without towing.",
    quickStats: [
      { value: "30", unit: "min", label: "Avg. Arrival" },
      { value: "OBD-II", unit: "", label: "Diagnostics" },
      { value: "On-Site", unit: "", label: "Repair" },
    ],
    overview: {
      title: "Expert Mechanics at Your Location",
      paragraphs: [
        "Mechanical problems range from simple belt replacements to complex engine issues. Before you pay for expensive towing to a workshop, let our mobile mechanics diagnose the problem on-site. Many issues can be fixed right where you're parked.",
        "Our service vehicles are mobile workshops equipped with OBD-II diagnostic scanners, multimeters, compression testers, and a comprehensive inventory of parts — belts, hoses, filters, fuses, sensors, and fluids. We identify the root cause, not just the symptoms.",
        "For issues that genuinely need a workshop, we provide an accurate diagnosis so you know exactly what's wrong before committing to repairs elsewhere. No guesswork, no unnecessary charges.",
      ],
      image: "/images/cardService/mechanical-fault.jpg",
    },
    features: [
      { title: "OBD-II Diagnostics", description: "Advanced scanner reads error codes from your vehicle's computer to pinpoint the exact issue.", icon: "tool" },
      { title: "On-Site Repairs", description: "Belt replacements, hose repairs, sensor swaps, fluid top-ups — many fixes done at your location.", icon: "speed" },
      { title: "Parts Inventory", description: "We carry belts, hoses, filters, fuses, sensors, and fluids for common vehicle makes and models.", icon: "check" },
      { title: "Transparent Diagnosis", description: "We explain the problem in plain language, show you the issue, and give options before starting work.", icon: "price" },
      { title: "All Systems Covered", description: "Engine, transmission, brakes, steering, suspension, electrical — our mechanics handle it all.", icon: "car" },
      { title: "Workshop Referral", description: "For complex repairs needing a lift, we provide diagnosis and recommend trusted workshops in Jaipur.", icon: "clock" },
    ],
    process: [
      { step: "01", title: "Describe the Issue", description: "Call +91-8955836514. Tell us what's happening — sounds, warning lights, symptoms." },
      { step: "02", title: "Mechanic Arrives", description: "A certified mechanic reaches you with diagnostic tools and commonly needed parts." },
      { step: "03", title: "Diagnose & Repair", description: "We run diagnostics, identify the root cause, and fix it on-site when possible." },
      { step: "04", title: "Verified & Done", description: "Repair tested and verified. If workshop service is needed, you get an accurate diagnosis to take with you." },
    ],
    faqs: [
      { question: "What kinds of repairs can you do on-site?", answer: "Belt and hose replacements, filter changes, fluid top-ups, sensor swaps, fuse replacements, minor electrical fixes, and more. Anything that doesn't require a vehicle lift." },
      { question: "What if the problem is too complex for on-site repair?", answer: "We provide a detailed diagnosis with error codes and our assessment. This saves you money at the workshop because they won't need to re-diagnose." },
      { question: "Do you carry parts for my car?", answer: "We stock parts for popular Indian and international brands — Maruti, Hyundai, Honda, Toyota, Tata, Mahindra, and more. For rare parts, we can source them quickly from local suppliers." },
      { question: "How do I know if I need a mechanic or a tow?", answer: "Call us and describe the symptoms. Our team will advise whether an on-site mechanic visit or towing is the better option." },
    ],
    relatedServices: ["emergency-breakdown", "battery-jumpstart", "towing"],
  },

  "emergency-breakdown": {
    title: "Emergency Breakdown",
    slug: "emergency-breakdown",
    description: "Immediate roadside help when your car breaks down",
    image: "/images/cardService/emergency-breakdown.png",
    heroImage: "/images/services/emergency-hero.jpg",
    heroTitle: "Emergency Breakdown Assistance",
    heroSubtitle: "Stranded? Help is on the way — now.",
    heroDescription: "When your engine stalls, overheats, or your car simply won't move, call us. Fast dispatch, expert diagnosis, on-site repair or safe towing. 24/7 across Jaipur.",
    quickStats: [
      { value: "24/7", unit: "", label: "Available" },
      { value: "<30", unit: "min", label: "Response" },
      { value: "500+", unit: "", label: "Rescues" },
    ],
    overview: {
      title: "Rapid Response for Every Roadside Emergency",
      paragraphs: [
        "A breakdown is stressful — steam from the hood, warning lights flashing, the engine refusing to start. RJ Roadside Assistance specializes in getting you out of these situations quickly and safely.",
        "Our emergency technicians carry diagnostic equipment, coolant, fluids, basic parts, and towing coordination capability. They assess the situation, stabilize your vehicle if it's overheating, and either fix the issue on-site or arrange safe transport to a workshop.",
        "Safety comes first. We position our vehicle to protect you from traffic, use warning indicators, and guide you to a safe spot. You're never alone during a breakdown — we keep you informed every step of the way.",
      ],
      image: "/images/cardService/emergency-breakdown.png",
    },
    features: [
      { title: "Fastest Response", description: "Emergency calls get top priority. Average arrival under 30 minutes across Jaipur.", icon: "speed" },
      { title: "Engine Overheating", description: "Coolant top-up, hose inspection, and radiator assessment to prevent costly engine damage.", icon: "tool" },
      { title: "On-Site Diagnosis", description: "OBD-II scanning and visual inspection to identify the problem before deciding next steps.", icon: "check" },
      { title: "Repair or Tow", description: "Fixable on-site? We repair it. Needs a workshop? We arrange safe towing immediately.", icon: "car" },
      { title: "Traffic Safety", description: "Warning signs, hazard positioning, and safety protocols to protect you from passing traffic.", icon: "clock" },
      { title: "Insurance Coordination", description: "For accident-related breakdowns, we help with documentation and insurance communication.", icon: "price" },
    ],
    process: [
      { step: "01", title: "Call for Help", description: "Dial +91-8955836514. Tell us your location and what happened — we'll guide you on immediate safety steps." },
      { step: "02", title: "Rapid Dispatch", description: "Emergency technician dispatched immediately with diagnostic tools and essential supplies." },
      { step: "03", title: "Assess & Act", description: "We diagnose the issue, stabilize overheating if needed, and repair on-site or coordinate towing." },
      { step: "04", title: "Resolved", description: "You're either driving again or your vehicle is safely at a trusted repair facility." },
    ],
    faqs: [
      { question: "My engine is overheating — what should I do right now?", answer: "Pull over safely, turn off the engine, and open the hood (carefully — don't touch the radiator cap). Call us immediately. Don't try to drive with an overheating engine — it can cause permanent damage." },
      { question: "What if the problem can't be fixed on the road?", answer: "We'll diagnose the issue, explain your options, and arrange professional towing to your preferred workshop or our trusted partner facility." },
      { question: "How is this different from your other services?", answer: "Emergency breakdown is our rapid-response service for any unexpected vehicle failure. Our other services (battery, tyre, etc.) target specific problems. If you're not sure what's wrong, call for emergency breakdown assistance." },
      { question: "Do you operate outside Jaipur city?", answer: "We primarily serve Jaipur city and its surrounding areas. For locations beyond our coverage, call us and we'll try to arrange assistance or refer a partner service." },
    ],
    relatedServices: ["battery-jumpstart", "mechanical-fault", "towing"],
  },
};
